pull_requests:
  do_not_increment_build_number: true

image: Visual Studio 2017

build:
  verbosity: minimal
  publish_nuget: false

skip_commits:
  files:
  - .gitattributes
  - .gitignore
  - README.md
  - CHANGELOG.md
  - LICENSE

skip_tags: true

test: off

build_script:
  
  - cmd: build-vs2017.cmd

